# Site settings
title: INFI
SEOTitle: Xerolen
header-img: img/index-header.jpg
email:  xerolen.xule@gmail.com
description: "Whatever happens tomorrow,we've had today!"
keyword: "前端开发,HTML,CSS,JS"
url: "http://xerolen.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xerolen/xerolen.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "The meaning of life is to give life meaning."
sidebar-avatar: /img/about-me.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     lexu-36
github_username:    xerolen
facebook_username:  LEXU36
# jianshu_username:   a13e7484dc21
# weibo_username:     Agcaiyun
# twitter_username:   none


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]
 


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统 建议使用 Disqus（http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241）
# Disqus settings（https://disqus.com/）
disqus_username: disqus_xerolen


# Analytics settings
# Baidu Analytics
# ba_track_id: 3b543188a9d990dd28391550251848bf

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "武汉",
        href: "http://www.jianshu.com/u/a13e7484dc21"
    },
    {
        title: "北京",
        href: "https://compelcode.com"
    }
]

